
elements_traits = [
  ["ElementTypeNull"        ,  0  ],
  ["ElementTypeUserDefined" , -1  ],
  ["NODE"                   ,  1  ],
  ["BAR_2"                  ,  2  ],
  ["BAR_3"                  ,  3  ],
  ["TRI_3"                  ,  3  ],
  ["TRI_6"                  ,  6  ],
  ["QUAD_4"                 ,  4  ],
  ["QUAD_8"                 ,  8  ],
  ["QUAD_9"                 ,  9  ],
  ["TETRA_4"                ,  4  ],
  ["TETRA_10"               ,  10 ],
  ["PYRA_5"                 ,  5  ],
  ["PYRA_14"                ,  14 ],
  ["PENTA_6"                ,  6  ],
  ["PENTA_15"               ,  15 ],
  ["PENTA_18"               ,  18 ],
  ["HEXA_8"                 ,  8  ],
  ["HEXA_20"                ,  20 ],
  ["HEXA_27"                ,  27 ],
  ["MIXED"                  , -1  ],
  ["PYRA_13"                ,  13 ],
  ["NGON_n"                 , -1  ],
  ["NFACE_n"                , -1  ],
  ["BAR_4"                  ,  4  ],
  ["TRI_9"                  ,  9  ],
  ["TRI_10"                 ,  10 ],
  ["QUAD_12"                ,  12 ],
  ["QUAD_16"                ,  16 ],
  ["TETRA_16"               ,  16 ],
  ["TETRA_20"               ,  20 ],
  ["PYRA_21"                ,  21 ],
  ["PYRA_29"                ,  29 ],
  ["PYRA_30"                ,  30 ],
  ["PENTA_24"               ,  24 ],
  ["PENTA_38"               ,  38 ],
  ["PENTA_40"               ,  40 ],
  ["HEXA_32"                ,  32 ],
  ["HEXA_56"                ,  56 ],
  ["HEXA_64"                ,  64 ],
  ["BAR_5"                  ,  5  ],
  ["TRI_12"                 ,  12 ],
  ["TRI_15"                 ,  15 ],
  ["QUAD_P4_16"             ,  16 ],
  ["QUAD_25"                ,  25 ],
  ["TETRA_22"               ,  22 ],
  ["TETRA_34"               ,  34 ],
  ["TETRA_35"               ,  35 ],
  ["PYRA_P4_29"             ,  29 ],
  ["PYRA_50"                ,  50 ],
  ["PYRA_55"                ,  55 ],
  ["PENTA_33"               ,  33 ],
  ["PENTA_66"               ,  66 ],
  ["PENTA_75"               ,  75 ],
  ["HEXA_44"                ,  44 ],
  ["HEXA_98"                ,  98 ],
  ["HEXA_125"               ,  125]
]

def element_name (n):
  return elements_traits[n][0]

def element_number_of_nodes(n):
  return elements_traits[n][1]

