#pragma once


namespace cgns {


enum class label {
  DataClass_t,
  GridLocation_t,
  PointSetType_t,
  BCDataType_t,
  DataType_t,
  GridConnectivityType_t,
  GridConnectivity_t,
  ZoneGridConnectivity_t,
  ZoneType_t,
  Zone_t,
  ZoneSubRegion_t,
  SimulationType_t,
  RigidGridMotionType_t,
  ArbitraryGridMotionType_t,
  ArbitraryGridMotion_t,
  WallFunction_t,
  WallFunctionType_t,
  Area_t,
  AreaType_t,
  ZoneBC_t,
  ZoneIterativeData_t,
  UserDefinedData_t,
  AverageInterface_t,
  Axisymmetry_t,
  BCDataSet_t,
  BCData_t,
  BCProperty_t,
  BC_t,
  BaseIterativeData_t,
  CGNSBase_t,
  CGNSLibraryVersion_t,
  ConvergenceHistory_t,
  DataArray_t,
  DataConversion_t,
  Descriptor_t,
  DimensionalExponents_t,
  DimensionalUnits_t,
  AdditionalUnits_t,
  AdditionalExponents_t,
  DiscreteData_t,
  FamilyBC_t,
  FamilyBCDataSet_t,
  FamilyName_t,
  AdditionalFamilyName_t,
  Family_t,
  FlowEquationSet_t,
  FlowSolution_t,
  GasModel_t,
  GeometryEntity_t,
  GeometryFile_t,
  GeometryFormat_t,
  GeometryReference_t,
  Gravity_t,
  GridConnectivity1to1_t,
  GridConnectivityProperty_t,
  GridCoordinates_t,
  IndexArray_t,
  IndexRange_t,
  IntegralData_t,
  InwardNormalList_t,
  Ordinal_t,
  OversetHoles_t,
  Periodic_t,
  ReferenceState_t,
  RigidGridMotion_t,
  Rind_t,
  RotatingCoordinates_t,
  GoverningEquations_t,
  GoverningEquationsType_t,
  BCType_t,
  BCTypeSimple_t,
  GasModelType_t,
  ViscosityModel_t,
  ViscosityModelType_t,
  ThermalConductivityModel_t,
  ThermalConductivityModelType_t,
  TurbulenceModel_t,
  TurbulenceModelType_t,
  TurbulenceClosure_t,
  TurbulenceClosureType_t,
  ThermalRelaxationModel_t,
  ThermalRelaxationModelType_t,
  ChemicalKineticsModel_t,
  ChemicalKineticsModelType_t,
  EMElectricFieldModel_t,
  EMElectricFieldModelType_t,
  EMMagneticFieldModel_t,
  EMMagneticFieldModelType_t,
  EMConductivityModel_t,
  EMConductivityModelType_t,
  AverageInterfaceType_t,
  AverageInterface_t,
  Elements_t,
  ElementType_t
};


} // cgns
